import test from 'node:test'
import assert from 'node:assert/strict'
import { areas, load, all, manifest } from '../index.js'
import { generate, derived, DERIVED_FIELDS } from '../datagen.js'

// Independently computed check values (shasum/md5/CRC catalog); shared by all
// four language ports of the datagen reference.
const BLOCK0 = 'b8cc3d1fcf7818feab07f224263256110eeb3b576a94ef8e7e439b48fc77998b'
const BLOCK1 = '64a3a04c326aae7efd121f8468df1ac90ead2ece1e952353903cbcb6ae47618d'

const SPECS = {
  t40: { kind: 'prng', seed: 'test', size: 40 },
  t32: { kind: 'prng', seed: 'test', size: 32 },
  t10: { kind: 'prng', seed: 'test', size: 10 },
  aaa: { kind: 'pattern', pattern: 'A', size: 5 },
  abc: { kind: 'pattern', pattern: 'abc', size: 8 },
  bin: { kind: 'pattern', patternBase64: '3q2+7w==', size: 6 },
  sl: { kind: 'slice', of: 't40', offset: 30, length: 6 },
  chain: { kind: 'slice', of: 'sl', offset: 0, length: 1 },
  over: { kind: 'slice', of: 't10', offset: 8, length: 8 },
  check: { kind: 'pattern', pattern: '123456789', size: 9 }
}

test('datagen check values', () => {
  assert.equal(generate(SPECS, 't32').toString('hex'), BLOCK0)
  assert.equal(generate(SPECS, 't40').toString('hex'), BLOCK0 + BLOCK1.slice(0, 16))
  assert.equal(generate(SPECS, 't10').toString('hex'), BLOCK0.slice(0, 20))
  assert.equal(generate(SPECS, 'aaa').toString('utf8'), 'AAAAA')
  assert.equal(generate(SPECS, 'abc').toString('utf8'), 'abcabcab')
  assert.equal(generate(SPECS, 'bin').toString('hex'), 'deadbeefdead')
  assert.equal(generate(SPECS, 'sl').toString('hex'), (BLOCK0 + BLOCK1.slice(0, 16)).slice(60, 72))

  assert.equal(derived(SPECS, 'aaa', 'md5'), 'f6a6263167c92de8644ac998b3c4e4d1')
  assert.equal(derived(SPECS, 'aaa', 'etag'), '"f6a6263167c92de8644ac998b3c4e4d1"')
  assert.equal(derived(SPECS, 'aaa', 'size'), '5')
  // CRC catalog check values over ASCII "123456789": 0xCBF43926 / 0xE3069283 / 0xAE8B14860A799888
  assert.equal(derived(SPECS, 'check', 'crc32B64'), Buffer.from('cbf43926', 'hex').toString('base64'))
  assert.equal(derived(SPECS, 'check', 'crc32cB64'), Buffer.from('e3069283', 'hex').toString('base64'))
  assert.equal(derived(SPECS, 'check', 'crc64nvmeB64'), Buffer.from('ae8b14860a799888', 'hex').toString('base64'))
  for (const f of DERIVED_FIELDS) derived(SPECS, 'sl', f)
})

test('datagen error cases', () => {
  assert.throws(() => generate(SPECS, 'nope'), /unknown dataset/)
  assert.throws(() => derived(SPECS, 'aaa', 'sha512'), /unknown derived data field/)
  assert.throws(() => generate(SPECS, 'chain'), /chained slices/)
  assert.throws(() => generate(SPECS, 'over'), /exceeds/)
})

test('manifest agreement', () => {
  assert.equal(areas.length, manifest.areas.length)
  let total = 0
  for (const entry of manifest.areas) {
    const file = load(entry.area)
    assert.equal(file.area, entry.area)
    assert.equal(file.vectors.length, entry.count)
    total += file.vectors.length
  }
  assert.equal(total, manifest.total)
  assert.throws(() => load('no-such-area'), /unknown area/)
})

test('root equals union of areas; ids unique and area-prefixed', () => {
  const files = all()
  assert.deepEqual(files.map(f => f.area), [...areas])
  const ids = new Set()
  for (const file of files) {
    for (const v of file.vectors) {
      assert.ok(!ids.has(v.id), `duplicate id ${v.id}`)
      ids.add(v.id)
      assert.ok(v.id.startsWith(`${file.area}-`), `${v.id} not prefixed with ${file.area}`)
    }
  }
  assert.equal(ids.size, manifest.total)
})

test('vector shape smoke', () => {
  for (const file of all()) {
    for (const v of file.vectors) {
      assert.ok(v.kind === 'api' || v.kind === 'signing', `${v.id}: kind`)
      assert.ok(v.title.length > 0)
      assert.equal(v.tags.filter(t => /^tier-[123]$/.test(t)).length, 1, `${v.id}: tier tags`)
      if (v.kind === 'api') {
        assert.ok(v.steps.length > 0, `${v.id}: steps`)
        for (const s of v.steps) {
          assert.ok(('operation' in s) !== ('http' in s), `${v.id}: step must have exactly one of operation/http`)
        }
      } else {
        assert.ok(v.expect.authorization.length > 0, `${v.id}: authorization`)
      }
    }
  }
})

test('full-corpus datagen pass', () => {
  // Every non-slice dataset must materialize (slices only re-read parent bytes,
  // and their bounds are validated by the corpus linter). Derived fields — each
  // of which regenerates its dataset internally — are exercised only where the
  // regenerated bytes are <= 1 MiB; the algorithms are size-independent and
  // pinned by check values above.
  const DERIVED_CAP = 1024 * 1024
  for (const file of all()) {
    for (const v of file.vectors) {
      if (v.kind !== 'api' || !v.data) continue
      for (const [name, spec] of Object.entries(v.data)) {
        const parentSize = spec.kind === 'slice' ? v.data[spec.of].size : spec.size
        if (spec.kind !== 'slice') {
          const bytes = generate(v.data, name)
          assert.equal(bytes.length, spec.size, `${v.id}/${name}: size`)
        }
        if (parentSize <= DERIVED_CAP) {
          for (const f of DERIVED_FIELDS) derived(v.data, name, f)
        }
      }
    }
  }
})
